### ISSUE TITLE
Using the invitation link while also logged in as a Google user

### ISSUE THREAD

**Issue by remcogerlich** [nens/nens-auth-client#58]
Chris Gooch of Parramatta tried to login on staging but as he was also logged in with his private Google account, he got an ugly error message, see screenshot.

The whole process and 403 errors were very confusing to him. I'm not sure what steps he actually tried, but maybe this situation should be tested to see what happens exactly.

![bug login with google](https://user-images.githubusercontent.com/294656/109475063-8a00c280-7a75-11eb-9a4b-c2cd52df6328.png)

**Comment by lexvand** [comment]
Based on my test experience: When opening an invitation link you are directed to the login page. Here you have the options to login through Google, specific Corporate ID or existing AWS Cognito credentials or create an account (sign up option). Chris will have opted for Google, instead of using his existing Lizard credentials (he will already have been registered with his work email through Lizard production).

As the login screen is the standard for AWS Cognito I guess there is no way to make it more clear to the user what could go wrong when choosing the wrong login option. 

This message of mismatching email between invitation and login is quite clear to me. The one you get when you log in with an unregistered Google/Corporate ID without an invitation is more ambiguous to me (nens/lizard-nxt#4754).

@caspervdw Any thoughts on this? Otherwise I think it can be closed.

**Comment by caspervdw** [comment]
I think this is precisely as you described.

Signing in with Google, Corporate ID or AWS Cognito/SSO credentials are all different methods which lead to different external user ids. So when Chris signs in via Google he really is "somebody else"  than if he signs in via AWS Cognito/SSO. So he can't use his work email privileges (access to lizard) or accept invitations intended for its work email.

From the perspective of Lizard you can't make the message more informative because there is no way to connect the private and work accounts.
Connecting accounts in general is a tricky subject which we avoid.
